<form class="auth-form" action="/pollweb/auth" method="post">
	<div class="form-field">
		<label for="email">Email: </label>
		<input class="text-input input" type="email" name="email"/>
	</div>
	<div class="form-field">
		<label for="password" class="auth-form__input">Password: </label>
		<input class="input text-input" type="password" name="password"/>
	</div>
	<div class="form-field">
    	<input class="btn" type="submit" name="login" value="Accedi" class="medium">
    </div>
</form>